baseurl = "https://blog.zzzmisa.com/"
title = "zzzmisa's blog"
languageCode = "ja-JP"

googleAnalytics = "UA-88635038-1"
hasCJKLanguage = true

[taxonomies]
  tag = "tags"

[params]
  dateformat = "Jan 2, 2006"
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/author.png"
  name = "ミサ"
  description = "<p>このブログについてと詳しいプロフィールは<a href='/about'>こちら</a>。</p>"
  twitter = "https://twitter.com/zzzmisa/"
  github = "https://github.com/zzzmisa/"
  mail = "https://docs.google.com/forms/d/e/1FAIpQLSdmZDfWbJXaHeG3EDmlgfXZXdfZw15Ot0gFwtpNbs3yIhTuJA/viewform"

[outputs]
  page = [ "HTML", "AMP" ]

[blackfriday]
  hrefTargetBlank = true
